{
  config,
  ...
}:
let
  notesDir = "${config.home.homeDirectory}/notes";
  notesGitCommands = config.luix.notesSync.commands;
in
{
  imports = [
    ./media
    ./presentations
    ./templates
    ./flashcards
  ];

  programs.nvf.settings.vim = {
    globals.maplocalleader = ",";

    keymaps = (import ./keymaps.nix { inherit notesDir; }) ++ [
      {
        mode = "n";
        key = "<leader>ngs";
        action = "<cmd>lua LuixNotesGit.run(${builtins.toJSON notesGitCommands.sync})<CR>";
        desc = "Sync notes";
      }
      {
        mode = "n";
        key = "<leader>ngu";
        action = "<cmd>lua LuixNotesGit.run(${builtins.toJSON notesGitCommands.push})<CR>";
        desc = "Push notes (upload)";
      }
      {
        mode = "n";
        key = "<leader>ngd";
        action = "<cmd>lua LuixNotesGit.run(${builtins.toJSON notesGitCommands.pull})<CR>";
        desc = "Pull notes (download)";
      }
      {
        mode = "n";
        key = "<leader>ngg";
        action = "<cmd>lua LuixNotesGit.lazygit(${builtins.toJSON notesGitCommands.sync})<CR>";
        desc = "Notes LazyGit";
      }
    ];

    binds.whichKey.register."<leader>n" = "+Notes";
    binds.whichKey.register."<leader>ng" = "+Notes Git";
    binds.whichKey.register."<leader>nj" = "+Journal";

    notes.neorg = {
      enable = true;
      treesitter.enable = true;
      setupOpts.load = {
        "core.defaults" = { };
        "core.concealer" = { };
        "core.ui.calendar" = { };
        "core.integrations.telescope" = { };
        "core.dirman" = {
          config = {
            workspaces.notes = notesDir;
            default_workspace = "notes";
            index = "index.norg";
          };
        };
      };
    };

    luaConfigRC.neorg-filetype = ''
      vim.api.nvim_create_autocmd("FileType", {
        pattern = "norg",
        callback = function()
          vim.opt_local.wrap = true
          vim.opt_local.linebreak = true
          vim.opt_local.spell = true
        end,
      })
    '';

    luaConfigRC.neorg-journal-overview = ''
      local journal_notes_dir = vim.fn.expand(${builtins.toJSON notesDir})

      LuixJournalOverview = {
        update_and_open = function()
          local journal_dir = journal_notes_dir .. "/journal"
          local overview_path = journal_notes_dir .. "/journal.norg"

          local entries = {}
          for _, file in ipairs(vim.fn.globpath(journal_dir, "**/*.norg", false, true)) do
            local rel = file:sub(#journal_dir + 2):gsub("%.norg$", "")
            local y, m, d = rel:match("^(%d+)[/%-](%d+)[/%-](%d+)$")
            if y then
              table.insert(entries, { y = tonumber(y), m = tonumber(m), d = tonumber(d), rel = rel })
            end
          end
          table.sort(entries, function(a, b)
            if a.y ~= b.y then return a.y > b.y end
            if a.m ~= b.m then return a.m > b.m end
            return a.d > b.d
          end)

          local lines = {
            "@document.meta",
            "title: Journal",
            "@end",
            "",
            "* Journal",
            "  Generated by <leader>njo -- manual edits will be overwritten.",
          }
          local cur_year, cur_month
          for _, e in ipairs(entries) do
            local stamp = os.time({ year = e.y, month = e.m, day = e.d, hour = 12 })
            if e.y ~= cur_year then
              table.insert(lines, "")
              table.insert(lines, "** " .. e.y)
              cur_year, cur_month = e.y, nil
            end
            if e.m ~= cur_month then
              table.insert(lines, "*** " .. os.date("%B", stamp))
              cur_month = e.m
            end
            table.insert(lines, string.format(
              "    - {:$/journal/%s:}[%s %d.]", e.rel, os.date("%A", stamp), e.d))
          end
          if #entries == 0 then
            table.insert(lines, "")
            table.insert(lines, "  No journal entries yet -- create one with <leader>njj.")
          end

          vim.fn.writefile(lines, overview_path)
          vim.cmd("edit! " .. vim.fn.fnameescape(overview_path))
        end,
      }
    '';

    luaConfigRC.neorg-notes-git = ''
      local notes_dir = vim.fn.expand(${builtins.toJSON notesDir})

      local function notes_terminal(cmd)
        local Terminal = require("toggleterm.terminal").Terminal
        Terminal:new({
          cmd = cmd,
          dir = notes_dir,
          direction = "float",
          close_on_exit = false,
          hidden = true,
        }):toggle()
      end

      local function notes_has_git()
        local stat = vim.uv and vim.uv.fs_stat or vim.loop.fs_stat
        return stat(notes_dir .. "/.git") ~= nil
      end

      LuixNotesGit = {
        run = notes_terminal,
        lazygit = function(sync_cmd)
          if vim.fn.executable("lazygit") == 0 then
            vim.notify("lazygit is not installed", vim.log.levels.ERROR)
            return
          end

          if notes_has_git() then
            notes_terminal("lazygit")
          else
            notes_terminal(sync_cmd .. " && lazygit")
          end
        end,
      }
    '';
  };
}
