# Do not modify this file! It was generated by `nixos-generate-config`
# for the Framework Laptop 13 (AMD Ryzen AI 300 Series).
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-ea0b42c2-5259-47cf-b400-2fe475dc7f27";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-ea0b42c2-5259-47cf-b400-2fe475dc7f27".device =
    "/dev/disk/by-uuid/ea0b42c2-5259-47cf-b400-2fe475dc7f27";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/60DB-A4D4";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
